### ISSUE TITLE
无法从zip安装，显示结构不正确

### ISSUE THREAD

**Issue by cxwx** [conwnet/shadowsocks-kodi#2]

**Comment by conwnet** [comment]
抱歉，我只测试了树莓派上安装的 LibreELEC 里面的 Kodi，请问您使用的是什么平台？

**Comment by cxwx** [comment]
ubuntu 平台 Mac 平台，电脑上的，安装不成功。

**Comment by conwnet** [comment]
> ubuntu 平台 Mac 平台，电脑上的，安装不成功。

在 ubuntu 或者 mac 上，您可以直接安装 shadowsocks 官方的客户端呀~

**Comment by cxwx** [comment]
是的～-～
